name: "[A] detect-version"

on:
  push:
    tags: [ '*' ]
    paths:
      - .github/workflows/act-detect-version.yaml

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: version
        uses: milaboratory/github-ci/actions/detect-version@v1-beta

    outputs:
      version-info: ${{ toJSON(steps.version.outputs) }}

  echo:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Test output
        env:
          V_INFO: ${{ needs.test.outputs.version-info }}
        run: |
          jq . <<<"${V_INFO}"
