name: "[A] env/set"

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths:
      - .github/workflows/act-env-set.yaml

  workflow_dispatch:

jobs:
  test-and-check:
    runs-on: ubuntu-latest

    steps:
      - uses: milaboratory/github-ci/actions/env/set@v2-beta
        with:
          json: |
            { "MY_VAR_1": "awesome-value-1",
              "NEW_VAR": "multiline\nvalue" }
          list: |
            OTHER_VAR=value with spaces

            low_case_var=12345

      - name: Test
        uses: milaboratory/github-ci/actions/action-test@v2
        with:
          test: |
            test_equals "MY_VAR_1" "awesome-value-1" "${MY_VAR_1}"
            test_equals "NEW_VAR" "multiline
            value" "${NEW_VAR}"
            test_equals "OTHER_VAR" "value with spaces" "${MY_VAR_1}"
            test_equals "low_case_var" "12345" "${low_case_var}"
