name: "[A] strings/replace"

# The only reason this test exists is to check action actually works
# All complex logic checks are performed by JS unit tests

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths:
      - .github/workflows/act-strings-replace.yaml

  workflow_dispatch:

jobs:
  test-replacer-works:
    runs-on: ubuntu-latest

    steps:
      - id: test
        uses: milaboratory/github-ci/actions/strings/replace@v2-beta
        with:
          input: |-
            line1 from1
            line2 from2
          rules: |
            ^from1 -> to1
            from2 -> to2

    outputs:
      result: ${{ steps.test.outputs.result }}

  check:
    runs-on: ubuntu-latest
    needs:
      - test-replacer-works

    steps:
      - id: tests
        uses: milaboratory/github-ci/actions/action-test@v1
        env:
          REPLACE_EXPECTED: |-
            line1 to1
            line2 to2
          REPLACE_ACTUAL: ${{ needs.test-replacer-works.outputs.result }}

        with:
          test: |
            test_equals "Replacer works" "${REPLACE_EXPECTED}" "${REPLACE_ACTUAL}"
