name: "[A] templates/jinja"

on:
  push:
    tags-ignore: [ '*' ]
    paths:
      - .github/workflows/act-templates-jinja.yaml

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - id: test1
        uses: milaboratory/github-ci/actions/templates/jinja@v1-beta
        with:
          template: |
            var1: '{{ var1 }}', var2: '{{ var2 }}'
          data: |
            {"var1": "value of var 1"}
          variables: var2=value of var 2

      - id: prepare-test2
        shell: bash
        run: |
          cat >my-test2-template.j2 <<EndOfTemplate
          env substitution: '{{ env.get('SOME_TPL_VAR', '') }}'
          EndOfTemplate
      - id: test2
        uses: milaboratory/github-ci/actions/templates/jinja@v1-beta
        env:
          SOME_TPL_VAR: 'value from test 2'
        with:
          template-file: my-test2-template.j2

      - id: prepare-test3
        shell: bash
        run: |
          cat >test3-template.j2 <<EndOfTemplate
          data substitution: '{{ somevar }}'
          EndOfTemplate

          cat >test3-data.yaml <<EndOfTemplate
          somevar: value from test 3
          EndOfTemplate
      - id: test3
        uses: milaboratory/github-ci/actions/templates/jinja@v1-beta
        with:
          template-file: test3-template.j2
          data-file: test3-data.yaml

      - id: test4
        uses: milaboratory/github-ci/actions/templates/jinja@v1-beta
        with:
          template: static text with no vars
          out-file: template-output.txt

    outputs:
      test1: ${{ steps.test1.outputs.data }}
      test2: ${{ steps.test2.outputs.data }}
      test3: ${{ steps.test3.outputs.data }}
      test4-file: ${{ steps.test4.outputs.out-file }}

  check:
    runs-on: ubuntu-latest
    needs:
      - tests

    steps:
      - name: Test output
        uses: milaboratory/github-ci/actions/action-test@v1
        env:
          TEST1_EXPECTED: "var1: 'value of var 1', var2: 'value of var 2'"
          TEST1_ACTUAL: ${{ needs.tests.outputs.test1 }}

          TEST2_EXPECTED: "env substitution: 'value from test 2'"
          TEST2_ACTUAL: ${{ needs.tests.outputs.test2 }}

          TEST3_EXPECTED: "data substitution: 'value from test 3'"
          TEST3_ACTUAL: ${{ needs.tests.outputs.test3 }}

          TEST4_EXPECTED: "template-output.txt"
          TEST4_ACTUAL: ${{ needs.tests.outputs.test4-file }}
        with:
          test: |
            # Check templates rendered what we expected

            test_equals "Test data 1" \
              "${TEST1_EXPECTED}" \
              "${TEST1_ACTUAL}"

            test_equals "Test data 2" \
              "${TEST2_EXPECTED}" \
              "${TEST2_ACTUAL}"

            test_equals "Test data 3" \
              "${TEST3_EXPECTED}" \
              "${TEST3_ACTUAL}"

            test_equals "Test file path" \
              "${TEST4_EXPECTED}" \
              "${TEST4_ACTUAL}"
