name: "[A] notify/telegram/*"

on:
  push:
    paths:
      - .github/workflows/act-notify-telegram-new.yaml

  workflow_dispatch:

jobs:
  stub:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: 'true'

      - uses: milaboratory/github-ci/actions/notify/telegram/release@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          product-name: 'TG Notify Test'
          version: '111'
          tag: 'v111'
