name: "[A] notify/telegram/review-required"

on:
  push:
    tags-ignore: [ '*' ]
    paths:
      - .github/workflows/act-notify-telegram-review-required.yaml

  workflow_dispatch:

jobs:
  with-reviewers:
    runs-on: ubuntu-latest
    name: "With reviewers"

    steps:
      - uses: milaboratory/github-ci/actions/notify/telegram/review-required@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          product-name: "'review-required' test"
          message: new version is ready to be released
          reviewers: |
            @UserOne
            @UserTwo

  no-reviewers:
    runs-on: ubuntu-latest
    name: "No reviewers"

    steps:
      - uses: milaboratory/github-ci/actions/notify/telegram/review-required@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          product-name: "'review-required' test"
          message: new version is ready to be released
