name: "[A] context"

on:
  push:
    paths:
      - .github/workflows/act-context.yaml
      - .github/workflows/act-context-base.yaml

  workflow_dispatch:

jobs:
  test-before-init:
    runs-on: ubuntu-latest

    steps:
      - id: context
        uses: milaboratory/github-ci/actions/context@v1-beta

    outputs:
      data: ${{ toJSON(steps.context.outputs) }}

  test-context-init:
    runs-on: ubuntu-latest

    needs:
      - test-before-init

    steps:
      - uses: milaboratory/github-ci/actions/context/init@v1-beta

  test-after-init:
    runs-on: ubuntu-latest

    needs:
      - test-context-init

    steps:
      - id: context
        uses: milaboratory/github-ci/actions/context@v1-beta


    outputs:
      data: ${{ toJSON(steps.context.outputs) }}

  check:
    runs-on: ubuntu-latest
    needs:
      - test-before-init
      - test-after-init

    steps:
      - name: Test output
        uses: milaboratory/github-ci/actions/action-test@v1

        env:
          CTX_BEFORE_INIT: ${{ needs.test-before-init.outputs.data }}
          CTX_AFTER_INIT: ${{ needs.test-after-init.outputs.data }}

        with:
          test: |
            keys_count=$(jq -r 'keys[]' <<<"${CTX_AFTER_INIT}" | wc -l)

            if [ "${keys_count}" = "0" ]; then
              fail_test "Empty context after init"
            fi

            jq 'keys[]' <<<"${CTX_AFTER_INIT}" |
              while read -r key; do
                test_not_empty "Check ${key}" "$(jq ".${key}" <<<"${CTX_AFTER_INIT}")"
              done
