name: "[A] context"

on:
  push:
    paths:
      - .github/workflows/act-context.yaml
      - .github/workflows/act-context-base.yaml

  workflow_dispatch:

jobs:
  test-context-init:
    runs-on: ubuntu-latest

    steps:
      - uses: milaboratory/github-ci/actions/context/init@v1-beta

  test-context:
    runs-on: ubuntu-latest

    needs:
      - test-context-init

    steps:
      - id: context
        uses: milaboratory/github-ci/actions/context@v1-beta

      - uses: milaboratory/github-ci/actions/context@v1-beta


    outputs:
      current-version: ${{ steps.context.outputs.current-version }}
      current-version-tag: ${{ steps.context.outputs.current-version-tag }}
      current-version-sha: ${{ steps.context.outputs.current-version-sha }}
      previous-version: ${{ steps.context.outputs.previous-version }}
      previous-version-tag: ${{ steps.context.outputs.previous-version-tag }}
      previous-version-sha: ${{ steps.context.outputs.previous-version-sha }}
      latest-version: ${{ steps.context.outputs.latest-version }}
      latest-version-tag: ${{ steps.context.outputs.latest-version-tag }}
      latest-version-sha: ${{ steps.context.outputs.latest-version-sha }}
      is-latest-version: ${{ steps.context.outputs.is-latest-version }}
      is-branch-head: ${{ steps.context.outputs.is-branch-head }}

  check:
    runs-on: ubuntu-latest
    needs:
      - test-context

    steps:
      - name: Test output
        uses: milaboratory/github-ci/actions/action-test@v1

        env:
          CTX_CONTENT: ${{ toJSON( needs.test-context.outputs ) }}

        with:
          test: |
            keys_count=$(jq -r 'keys[]' <<<"${CTX_CONTENT}" | wc -l)

            if [ "${keys_count}" = "0" ]; then
              fail_test "Empty context after init"
            fi

            jq 'keys[]' <<<"${CTX_CONTENT}" |
              while read -r key; do
                test_not_empty "Check ${key}" "$(jq ".${key}" <<<"${CTX_CONTENT}")"
              done
