name: "[A] detect-version"

on:
  push:
    paths:
      - .github/workflows/act-detect-version.yaml

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: version-detector
        uses: milaboratory/github-ci/actions/detect-version@v1-beta

    outputs:
      current-version: ${{ steps.version-detector.outputs.current-version }}
      current-tag: ${{ steps.version-detector.outputs.current-tag }}
      current-sha: ${{ steps.version-detector.outputs.current-sha }}

      previous-version: ${{ steps.version-detector.outputs.previous-version }}
      previous-tag: ${{ steps.version-detector.outputs.previous-tag }}
      previous-sha: ${{ steps.version-detector.outputs.previous-sha }}

      latest-version: ${{ steps.version-detector.outputs.latest-version }}
      latest-tag: ${{ steps.version-detector.outputs.latest-tag }}
      latest-sha: ${{ steps.version-detector.outputs.latest-sha }}

      is-branch-head: ${{ steps.version-detector.outputs.is-branch-head }}

  echo:
    runs-on: ubuntu-latest
    needs:
      - detect-version

    steps:
      - name: Test output
        run: |
          echo "Curr Version: ${{ needs.detect-version.outputs.current-version }}"
          echo "Curr Tag: ${{ needs.detect-version.outputs.current-tag }}"
          echo "Curr Sha: ${{ needs.detect-version.outputs.current-sha }}"

          echo "Prev Version: ${{ needs.detect-version.outputs.previous-version }}"
          echo "Prev Tag: ${{ needs.detect-version.outputs.previous-tag }}"
          echo "Prev Sha: ${{ needs.detect-version.outputs.previous-sha }}"

          echo "Latest Version: ${{ needs.detect-version.outputs.latest-version }}"
          echo "Latest Tag: ${{ needs.detect-version.outputs.latest-tag }}"
          echo "Latest Sha: ${{ needs.detect-version.outputs.latest-sha }}"

          echo "Is branch HEAD: ${{ needs.detect-version.outputs.is-branch-head }}"

