name: "[A] templates/jinja"

on:
  workflow_dispatch:

jobs:
  render-template:
    runs-on: ubuntu-latest

    steps:
      - id: tpl
        uses: milaboratory/github-ci/actions/templates/jinja@v1-beta
        with:
          template: |
            Var1 value is: '{{ var1 }}'
            Var2 value is: '{{ var2 }}'
          data: |
            {"var1": "value of var1"}
          variables: |
            var2=value of var 2

    outputs:
      out-file: ${{ steps.tpl.outputs.out-file }}
      data: ${{ steps.tpl.outputs.data }}

  check:
    runs-on: ubuntu-latest
    needs:
      - render-template

    steps:
      - name: Test output
        env:
          DATA: ${{ needs.render-template.outputs.data }}
        run: |
          expected_result="Var1 value is: 'value of var1'
          Var2 value is: 'value of var 2'"

          [ "${expected_result}" = "${DATA}" ]
