name: "[A] docker/push"

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths:
      - .github/workflows/act-docker-push.yaml

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build stub docker image
        working-directory: ./docker
        run: |
          docker build --tag test:0.0.1 .

      - id: docker-push
        uses: milaboratory/github-ci/actions/docker/push@v2-beta
        with:
          auth-token: ${{ secrets.GITHUB_TOKEN }}
          source: 'test:0.0.1'
          registry: ghcr.io
          targets: |
            ${{ github.repository }}/test:0.0.1
            ${{ github.repository }}/test:tralala
            ${{ github.repository }}/test:latest-dev

    outputs:
      pushed: ${{ steps.docker-push.outputs.pushed }}
      pushed-json: ${{ steps.docker-push.outputs.pushed-json }}

  check:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Check tags pushed
        uses: milaboratory/github-ci/actions/action-test@v1
        env:
          PUSHED_EXPECTED: |-
            ghcr.io/${{ github.repository }}/test:0.0.1
            ghcr.io/${{ github.repository }}/test:tralala
            ghcr.io/${{ github.repository }}/test:latest-dev
          PUSHED_ACTUAL: ${{ needs.test.outputs.pushed }}

          JSON_EXPECTED: |-
            ["ghcr.io/${{ github.repository }}/test:0.0.1","ghcr.io/${{ github.repository }}/test:tralala","ghcr.io/${{ github.repository }}/test:latest-dev"]
          JSON_ACTUAL: ${{ needs.test.outputs.pushed-json }}
        with:
          test: |
            test_equals "Pushed tags" "${PUSHED_EXPECTED}" "${PUSHED_ACTUAL}"
            test_equals "JSON" "${JSON_EXPECTED}" "${JSON_ACTUAL}"
