name: "[A] notify/telegram/*"

on:
  push:
    paths:
      - .github/workflows/act-notify-telegram-new.yaml

  workflow_dispatch:

jobs:
  stub:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: 'true'
