name: "[A] notify/telegram/release"

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths:
      - .github/workflows/act-notify-telegram-release.yaml

  workflow_dispatch:

jobs:
  notify-release-failed:
    name: "'Release failed'"
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/notify/telegram/release-failed@v2-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          product-name: 'TG Notify Test'
          version: '111'
          tag: 'v111'

          additional-info: "Additional text at the end of release failure notification"

  notify-new-release:
    name: "'New release'"
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/notify/telegram/release-ready@v2-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          product-name: 'TG Notify Test'
          version: '111'
          tag: 'v111'

          docker-images: ''
          maven-packages: ''
          links: |
            [ "https://awesome.me/" ]

          additional-info: "Additional text at the end of new release notification"
