name: "[A] miaws"

on:
  push:
    tags-ignore: [ '*' ]
    paths:
      - .github/workflows/act-miaws.yaml

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: milaboratory/github-ci/actions/miaws/configure@v1-beta
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: milaboratory/github-ci/actions/miaws@v1-beta
        with:
          args: --help
