name: "[A] java/gradle/properties/read"

on:
  push:
    tags-ignore: [ '*' ]
    paths:
      - .github/workflows/act-java-gradle-properties-read.yaml
      - gradle/

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: props
        uses: milaboratory/github-ci/actions/java/gradle/properties/read@v2-beta
        with:
          project-dir: ./gradle
          project-name: ''

    outputs:
      all-props: ${{ toJSON(steps.props.outputs) }}

  check:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: milaboratory/github-ci/actions/action-test@v1
        env:
          PROJECT_PROPS: ${{ needs.test.outputs.all-props }}
        with:
          run: |
            read_prop() {
              local _prop_name="${1}"

              jq ".${_prop_name}" <<<"${PROJECT_PROPS}"
            }

            test_equals "stub" "$(read_prop "name")"
            test_equals "group" "$(read_prop "com.milaboratory.stub")"
