name: "[A] notify/telegram/*"

on:
  push:
    paths:
      - .github/workflows/act-notify-telegram.yaml

  workflow_dispatch:

jobs:
  send-release-ready:
    runs-on: ubuntu-latest
    name: "'Release ready'"

    steps:
      - uses: milaboratory/github-ci/actions/notify/telegram/release-ready@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          product-name: 'TG Notify Test'
          release-tag: 'v0.11.1'

          docker-images: |
            [ "path/to/image:one", "path/to/image:two" ]

          additional-info: |
            some additional info at the end of the message

  send-build-ready-dev:
    runs-on: ubuntu-latest
    name: "'Build ready' for dev"

    steps:
      - uses: milaboratory/github-ci/actions/notify/telegram/build-ready@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          product-name: 'TG Notify Test'
          build-version: '0.11.1-2-dev'
          build-category: 'dev'

          docker-images: |
            [ "path/to/image:one", "path/to/image:two" ]

          additional-info: |
            some additional info at the end of the message

  send-build-ready-release:
    runs-on: ubuntu-latest
    name: "'Build ready' for release"

    steps:
      - uses: milaboratory/github-ci/actions/notify/telegram/build-ready@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          product-name: 'TG Notify Test'
          build-version: '0.11.1-2-release'
          build-category: 'release'

          docker-images: |
            [ "path/to/image:one", "path/to/image:two" ]

          additional-info: |
            some additional info at the end of the message

  send-build-failed:
    runs-on: ubuntu-latest
    name: "'Build failed'"

    steps:
      - uses: milaboratory/github-ci/actions/notify/telegram/build-failed@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          product-name: 'TG Notify Test'
          build-version: '0.11.1-2-failed'
          build-category: 'dev'

          additional-info: |
            some additional info at the end of the message
