name: "[A] env/set"

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths:
      - .github/workflows/act-env-set.yaml

  workflow_dispatch:

jobs:
  test-and-check:
    runs-on: ubuntu-latest

    steps:
      - uses: milaboratory/github-ci/actions/env/set@v2-beta
        with:
          json: |
            { "MY_VAR_1": "awesome-value-1",
              "NEW_VAR": "multiline\nvalue" }
          list: |
            OTHER_VAR=value with spaces

            low_case_var=12345

      - uses: milaboratory/github-ci/actions/env/set@v2-beta
        with:
          json: |
            { "MASKED_JSON": "the masked value set from JSON" }
          list: |
            MASKED_LIST=the masked value set from list
          mask-values: true

      - name: Test
        uses: milaboratory/github-ci/actions/action-test@v2
        with:
          test: |
            test_equals "MY_VAR_1" "awesome-value-1" "${MY_VAR_1}"
            test_equals "NEW_VAR" "multiline
            value" "${NEW_VAR}"
            test_equals "OTHER_VAR" "value with spaces" "${OTHER_VAR}"
            test_equals "low_case_var" "12345" "${low_case_var}"

            echo "Masked JSON: '${MASKED_JSON}'"
            echo "Masked list: '${MASKED_LIST}'"
            ghwa_notice "Check the value '${MASKED_JSON}' is masked in logs"
            ghwa_notice "Check the value '${MASKED_LIST}' is masked in logs"
