name: "[A] strings/replace"

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths:
      - .github/workflows/act-strings-replace.yaml

  workflow_dispatch:

jobs:
  test-multiple-rules-1:
    runs-on: ubuntu-latest

    steps:
      - id: test
        uses: milaboratory/github-ci/actions/strings/replace@v2-beta
        with:
          input: |-
            line1 from1
            line2 from1
            line3 rfom1
            line4 from2
            line5 from2
          rules: |
            from1 -> to1
            from2 -> to2

    outputs:
      result: ${{ steps.test.outputs.result }}

  test-multiple-rules-2:
    runs-on: ubuntu-latest

    steps:
      - id: test
        uses: milaboratory/github-ci/actions/strings/replace@v2-beta
        with:
          input: |-
            line1 no match
          rules: |
            from1 -> to1
            from2 -> to2

    outputs:
      result: ${{ steps.test.outputs.result }}

  test-multiple-rules-3:
    runs-on: ubuntu-latest

    steps:
      - id: test
        uses: milaboratory/github-ci/actions/strings/replace@v2-beta
        with:
          input: ''
          rules: |
            from1 -> to1
            from2 -> to2

    outputs:
      result: ${{ steps.test.outputs.result }}

  check:
    runs-on: ubuntu-latest
    needs:
      - test-multiple-rules-1
      - test-multiple-rules-2
      - test-multiple-rules-3

    steps:
      - id: tests
        uses: milaboratory/github-ci/actions/action-test@v1
        env:
          MULTIPLE_1_EXPECTED: |-
            line1 to1
            line2 to1
            line3 rfom1
            line4 to2
            line5 to2
          MULTIPLE_1_ACTUAL: ${{ needs.test-multiple-rules-1.outputs.result }}

          MULTIPLE_2_EXPECTED: |-
            line1 no match
          MULTIPLE_2_ACTUAL: ${{ needs.test-multiple-rules-2.outputs.result }}

          MULTIPLE_3_EXPECTED: ''
          MULTIPLE_3_ACTUAL: ${{ needs.test-multiple-rules-3.outputs.result }}

        with:
          test: |
            test_equals "Multiple rules 1" "${MULTIPLE_1_EXPECTED}" "${MULTIPLE_1_ACTUAL}"
            test_equals "Multiple rules 2" "${MULTIPLE_2_EXPECTED}" "${MULTIPLE_2_ACTUAL}"
            test_equals "Multiple rules 3" "${MULTIPLE_3_EXPECTED}" "${MULTIPLE_3_ACTUAL}"
