name: "[A] shell"

on:
  workflow_dispatch:

jobs:
  run-shell:
    runs-on: ubuntu-latest

    steps:
      - id: sh
        uses: milaboratory/github-ci/actions/shell@v1-beta
        with:
          run: |
            echo "myvalue 1"
            echo "myvalue 2"

            ghwa_set_output "myvar" "myvalue 3"

    outputs:
      data: ${{ steps.sh.outputs.data }}

  check:
    runs-on: ubuntu-latest
    needs:
      - run-shell

    steps:
      - name: Test output
        env:
          OUTPUT: ${{ needs.run-shell.outputs.stdout }}
        run: |
          echo "stdout is: ${OUTPUT}"

          echo "All outputs are:"
          jq . <<EndOfJSON
            ${{ needs.run-shell.outputs.data }}
          EndOfJSON
