name: "[A] notify/telegram/*"

on: [workflow_dispatch]

jobs:
  send-release-ready:
    runs-on: ubuntu-latest
    name: Send Telegram message

    steps:
      - uses: milaboratory/github-ci/actions/notify/telegram/release-ready@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          product-name: 'TG Notify Test'
          release-tag: 'v0.11.1'

          docker-images: |
            [ "path/to/image:one", "path/to/image:two" ]

          additional-info: |
            some additional info at the end of the message

  send-dev-build-ready:
    runs-on: ubuntu-latest
    name: Send Telegram message

    steps:
      - uses: milaboratory/github-ci/actions/notify/telegram/dev-build-ready@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          product-name: 'TG Notify Test'
          build-version: '0.11.1-2-master'
          build-category: 'dev'

          docker-images: |
            [ "path/to/image:one", "path/to/image:two" ]

          additional-info: |
            some additional info at the end of the message

  send-build-failed:
    runs-on: ubuntu-latest
    name: Send Telegram message

    steps:
      - uses: milaboratory/github-ci/actions/notify/telegram/build-failed@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          product-name: 'TG Notify Test'
          build-version: '0.11.1-2-master'
          build-category: 'dev'

          additional-info: |
            some additional info at the end of the message
