name: "[A] notify/telegram/release"

on:
  push:
    paths:
      - .github/workflows/act-notify-telegram-release.yaml

  workflow_dispatch:

jobs:
  notify-release:
    name: "'New release'"
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/notify/telegram/release@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          product-name: 'TG Notify Test'
          version: '111'
          tag: 'v111'
