name: "[A] helpers/safe-run"

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths:
      - .github/workflows/act-helpers-safe-run.yaml

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: milaboratory/github-ci/actions/helpers/safe-run@v2-beta
        with:
          script-path: ./assets/safe-run/absent.sh

      - uses: actions/checkout@v2
      - uses: milaboratory/github-ci/actions/helpers/safe-run@v2-beta
        with:
          script-path: ./assets/safe-run/not-executable.sh
      - uses: milaboratory/github-ci/actions/helpers/safe-run@v2-beta
        with:
          script-path: ./assets/safe-run/executable.sh
