name: "[A] docker/publish-github"

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Build stub docker image
        working-directory: ./docker
        run: |
          ls
          pwd
          docker build --tag test:0.0.1 .

      - id: docker-publish
        uses: milaboratory/github-ci/actions/docker/publish-github@v1-beta
        with:
          tag-name: test
          tag-version: 0.0.1
          update-latest: false

    outputs:
      versioned: ${{ steps.docker-publish.outputs.versioned-tag }}
      latest: ${{ steps.docker-publish.outputs.latest-tag }}
      latest-pushed: ${{ steps.docker-publish.outputs.latest-tag-pushed }}

  check:
    runs-on: ubuntu-latest
    needs:
      - build-and-publish

    steps:
      - name: Test output
        run: |
          echo "Versioned tag: ${{ needs.build-and-publish.outputs.versioned }}"
          echo "Latest tag: ${{ needs.build-and-publish.outputs.latest }}"
          echo "Latest tag pushed: ${{ needs.build-and-publish.outputs.latest-pushed }}"
