# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Experiments with our workflows

on:
  create:
  workflow_dispatch:

jobs:
  detect-version:
    runs-on: ubuntu-latest

    uses: milaboratory/github-ci/.github/workflows/autodetect-version.yaml@v1.x

  check:
    runs-on: ubuntu-latest
    needs:
      - detect-version

    steps:
      - name: Test output
        run: echo The detected version is: ${{ needs.detect-version.outputs.version }}

