# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Autodetect-version action check

on:
  create:
  workflow_dispatch:

jobs:
  detect-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: version-detector
        uses: milaboratory/github-ci/actions/autodetect-version@v1

    outputs:
      version: ${{ steps.version-detector.outputs.version }}

  check:
    runs-on: ubuntu-latest
    needs:
      - detect-version

    steps:
      - name: Test output
        run: |
          echo "The detected version is: ${{ needs.detect-version.outputs.version }}"

