name: "[B] notify/test"

on:
  push:
    paths:
      - .github/workflows/blk-notify-test.yaml

  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v1

    outputs:
      status: ${{ job.status }}

  notify-tests:
    name: Notify tests ready
    runs-on: ubuntu-latest

    if: always()

    needs:
      - init

    steps:
      - uses: milaboratory/github-ci/blocks/notify/test@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          tests-status: ${{ needs.init.outputs.status }}
          product-name: 'notify/tests block test'
