name: "[B] java/publish/docker"

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths:
      - .github/workflows/blk-java-publish-docker.yaml

  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - uses: milaboratory/github-ci/actions/context/init@v1

  publish:
    runs-on: ubuntu-latest

    needs:
      - init

    steps:
      - id: context
        uses: milaboratory/github-ci/actions/context@v1

      - uses: actions/checkout@v2

      - shell: bash
        env:
          CURRENT_VERSION: ${{ steps.context.outputs.current-version }}
        run: |
          docker build --tag "stub-docker:${CURRENT_VERSION}" ./docker

      - uses: milaboratory/github-ci/blocks/java/publish/docker@v2-beta
        with:
          project: stub-docker
          github-token: ${{ secrets.GITHUB_TOKEN }}
