name: "[B] release/s3"

on:
  push:
    tags: [ '*' ]
    paths:
      - .github/workflows/blk-release-s3.yaml

  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v1

      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v1
        with:
          name: release-s3-test
          path: assets/release-s3/

  upload-to-s3-version:
    name: Upload artifact to S3
    runs-on: ubuntu-latest

    needs:
      - init

    steps:
      - uses: milaboratory/github-ci/blocks/release/s3@v1-beta
        with:
          artifact-name: 'release-s3-test'
          add-version: 'true'

          s3-region: 'eu-central-1'
          s3-bucket: 'milaboratory-artefacts-public-files'
          s3-path: 'cdn/internal/ci/${{ github.repository }}/release-s3-test'

          s3-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
          s3-key-secret: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

  upload-to-s3-no-version:
    name: Upload artifact to S3
    runs-on: ubuntu-latest

    needs:
      - init

    steps:
      - uses: milaboratory/github-ci/blocks/release/s3@v1-beta
        with:
          artifact-name: 'release-s3-test'
          add-version: 'false'

          s3-region: 'eu-central-1'
          s3-bucket: 'milaboratory-artefacts-public-files'
          s3-path: 'cdn/internal/ci/${{ github.repository }}/release-s3-test'

          s3-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
          s3-key-secret: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
