name: "[B] release/s3"

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths:
      - .github/workflows/blk-release-s3.yaml

  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v1

      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v1
        with:
          name: release-s3-test
          path: assets/release-s3/

  upload-to-s3-version-sha:
    name: Upload to S3 (+version, +sha)
    runs-on: ubuntu-latest

    needs:
      - init

    steps:
      - id: s3
        uses: milaboratory/github-ci/blocks/release/s3@v2-beta
        with:
          artifact-name: 'release-s3-test'
          add-version: 'true'
          add-sha: 'true'

          s3-region: 'eu-central-1'
          s3-bucket: 'milaboratory-artefacts-public-files'
          s3-path: 'cdn/internal/ci/${{ github.repository }}/release-s3-test'

          s3-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
          s3-key-secret: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

          alternative-urls: |
            ^/cdn/internal/ -> https://example.com/awesome/

    outputs:
      download: ${{ steps.s3.outputs.download }}

  upload-to-s3-version:
    name: Upload to S3 (+version, -sha)
    runs-on: ubuntu-latest

    needs:
      - init

    steps:
      - uses: milaboratory/github-ci/blocks/release/s3@v2-beta
        with:
          artifact-name: 'release-s3-test'
          add-version: 'true'
          add-sha: 'false'

          s3-region: 'eu-central-1'
          s3-bucket: 'milaboratory-artefacts-public-files'
          s3-path: 'cdn/internal/ci/${{ github.repository }}/release-s3-test'

          s3-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
          s3-key-secret: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

  upload-to-s3-sha:
    name: Upload to S3 (-version, +sha)
    runs-on: ubuntu-latest

    needs:
      - init

    steps:
      - uses: milaboratory/github-ci/blocks/release/s3@v2-beta
        with:
          artifact-name: 'release-s3-test'
          add-version: 'false'
          add-sha: 'true'

          s3-region: 'eu-central-1'
          s3-bucket: 'milaboratory-artefacts-public-files'
          s3-path: 'cdn/internal/ci/${{ github.repository }}/release-s3-test'

          s3-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
          s3-key-secret: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

  upload-to-s3-sha-8:
    name: Upload to S3 (-version, +sha 8)
    runs-on: ubuntu-latest

    needs:
      - init

    steps:
      - uses: milaboratory/github-ci/blocks/release/s3@v2-beta
        with:
          artifact-name: 'release-s3-test'
          add-version: 'false'
          add-sha: '8'

          s3-region: 'eu-central-1'
          s3-bucket: 'milaboratory-artefacts-public-files'
          s3-path: 'cdn/internal/ci/${{ github.repository }}/release-s3-test'

          s3-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
          s3-key-secret: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

  upload-to-s3-no-change:
    name: Upload to S3 (-version, -sha)
    runs-on: ubuntu-latest

    needs:
      - init

    steps:
      - id: s3
        uses: milaboratory/github-ci/blocks/release/s3@v2-beta
        with:
          artifact-name: 'release-s3-test'
          add-version: 'false'
          add-sha: 'false'

          s3-region: 'eu-central-1'
          s3-bucket: 'milaboratory-artefacts-public-files'
          s3-path: 'cdn/internal/ci/${{ github.repository }}/release-s3-test'

          s3-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
          s3-key-secret: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

    outputs:
      download: ${{ steps.s3.outputs.download }}

  check:
    name: Check outputs
    runs-on: ubuntu-latest

    needs:
      - upload-to-s3-version-sha
      - upload-to-s3-no-change

    steps:
      - uses: milaboratory/github-ci/actions/action-test@v2
        env:
          ALTERNATIVE_EXPECTED: 'https://example.com/awesome/'
          ALTERNATIVE_ACTUAL: ${{ needs.upload-to-s3-version-sha.outputs.download }}

          DEFAULT_EXPECTED: 'https://milaboratory-artefacts-public-files.s3.eu-central-1.amazonaws.com/'
          DEFAULT_ACTUAL: ${{ needs.upload-to-s3-no-change.outputs.download }}
        with:
          test: |
            test_contains "Link alteration" "${ALTERNATIVE_EXPECTED}" "${ALTERNATIVE_ACTUAL}"
            test_contains "Default links" "${DEFAULT_EXPECTED}" "${DEFAULT_ACTUAL}"
