name: "[B] notify"

on:
  push:
    paths:
      - .github/workflows/blk-notify.yaml

  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v1

  notify-success:

    name: Notify (success)
    runs-on: ubuntu-latest

    if: success()

    needs:
      - init

    steps:
      - uses: milaboratory/github-ci/blocks/notify/build/success@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}
          product-name: 'TG Notify Test'
          docker-images: '["a/b/c:d"]'

  fail:
    runs-on: ubuntu-latest
    needs:
      - init

    steps:
      - shell: bash
        run: exit 1

  notify-failure:

    name: Notify (failure)
    runs-on: ubuntu-latest

    if: failure()

    needs:
      - fail

    steps:
      - name: Report build failure to Telegram
        uses: milaboratory/github-ci/blocks/notify/build/failure@v1-beta
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}
          product-name: 'TG Notify Test'
