name: "[B] java/test"

on:
  push:
    paths:
      - .github/workflows/blk-java-test.yaml

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: milaboratory/github-ci/actions/context/init@v1
      - uses: milaboratory/github-ci/actions/aws/configure@v1
        with:
          key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
          key-secret: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
          region: 'eu-central-1'

      - uses: milaboratory/github-ci/blocks/java/test@v1-beta
        with:
          project: 'stub-lib'
          tasks: 'test'
          project-dir: './gradle'

          java-version: '11'

          s3-bucket: 'milaboratory-artefacts-public-files'
