# This workflow will do a clean install of node dependencies,
# cache/restore them, build the source code and run tests across different OS

name: Build electron app check

on:
  workflow_dispatch: {}

jobs:
  build-linux:
    uses: milaboratory/github-ci/.github/workflows/node-build-electron-app.yaml@v1-beta
    with:
      node-version: '14.x'
      os: 'ubuntu-latest'
      app-name-slug: 'some-test-app'
      npm-build-script: 'build'

  build-macos:
    uses: milaboratory/github-ci/.github/workflows/node-build-electron-app.yaml@v1-beta
    with:
      node-version: '14.x'
      os: 'macos-latest'
      app-name-slug: 'some-test-app'
      npm-build-script: 'build'
