# This workflow will do a clean install of node dependencies,
# cache/restore them, build the source code and run tests across different OS

name: Build electron app check

on:
  push:
    tags: [ '*' ]
  workflow_dispatch: {}

jobs:
  build-linux:
    uses: milaboratory/github-ci/.github/workflows/node-build-electron-app.yaml@v1-beta
    with:
      node-version: '14.x'
      os: 'ubuntu-latest'
      app-name-slug: 'some-test-app'
      build-script-name: 'electron:build'
      notify-telegram-target: 95899978

  build-macos:
    uses: milaboratory/github-ci/.github/workflows/node-build-electron-app.yaml@v1-beta
    with:
      node-version: '14.x'
      os: 'macos-latest'
      app-name-slug: 'some-test-app'
      build-script-name: 'electron:build'
      notify-telegram-target: 95899978
