# This workflow will do a clean install of node dependencies,
# cache/restore them, build the source code and run tests across different OS

name: Build electron app check

on:
  push:
    tags: [ '*' ]
  workflow_dispatch: {}

jobs:
  run:
    uses: milaboratory/github-ci/.github/workflows/node-build-electron-app.yaml@v1-beta
    with:
      node-version: '14.x'
      os: |
        ['ubuntu-latest', 'macos-latest']
      app-name-slug: 'some-test-app'
      build-script-name: 'electron:build'
      project-dir: './node'
      notify-telegram: true
    secrets:
      TELEGRAM_NOTIFICATION_TARGET: "95899978"
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
