# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Detect-version action check

on:
  workflow_dispatch:

jobs:
  detect-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: version-detector
        uses: milaboratory/github-ci/actions/detect-version@v1-beta

    outputs:
      version: ${{ steps.version-detector.outputs.version }}
      tag: ${{ steps.version-detector.outputs.tag }}
      sha: ${{ steps.version-detector.outputs.sha }}
      prev-version: ${{ steps.version-detector.outputs.prev-version }}
      prev-tag: ${{ steps.version-detector.outputs.prev-tag }}
      prev-sha: ${{ steps.version-detector.outputs.prev-sha }}

  check:
    runs-on: ubuntu-latest
    needs:
      - detect-version

    steps:
      - name: Test output
        run: |
          echo "Version: ${{ needs.detect-version.outputs.version }}"
          echo "Tag: ${{ needs.detect-version.outputs.tag }}"
          echo "Sha: ${{ needs.detect-version.outputs.sha }}"
          echo "Prev Version: ${{ needs.detect-version.outputs.prev-version }}"
          echo "Prev Tag: ${{ needs.detect-version.outputs.prev-tag }}"
          echo "Prev Sha: ${{ needs.detect-version.outputs.prev-sha }}"

