name: Dump Env

on:
  push:
    tags-ignore: [ '*' ]
    branches: [ 'master' ]
    paths:
      - .github/workflows/dump-env.yaml

  workflow_dispatch:

jobs:
  dump-env:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    name: Dump env vars
    steps:
      - run: env
        shell: bash
