name: Dump Env (Docker)

on: [workflow_dispatch]

jobs:
  dump-env:
    runs-on: ubuntu-latest
    name: Dump env vars inside docker action
    steps:
      - uses: milaboratory/workflow-experiments/dump-env-action@master
