name: Dump Env

on:
  push:
    paths:
      - .github/workflows/dump-env.yaml

  workflow_dispatch:

jobs:
  dump-env:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    name: Dump env vars
    steps:
      - name: Prepare env for Java application build
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - run: env
        shell: bash
