name: Input-output communication demo

on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2

      - id: foo
        uses: milaboratory/github-ci/actions/hello-world@v1.x
        with:
          who-to-greet: 'Mona the Octocat'

      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
    outputs:
      random-number: ${{ steps.foo.outputs.random-number }}

  hello-world-2-job:
    runs-on: ubuntu-latest
    name: A job to say hello again
    needs:
      - hello_world_job

    steps:
      - run: |
          echo "The same random number, once again with the surroundings: ${{ toJSON(needs.hello_world_job) }}"
