name: Send test notification

on: [workflow_dispatch]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    name: Send Telegram message

    steps:
      - uses: milaboratory/github-ci/actions/notify/templates/release-ready@v1
        with:
          telegram-target: 95899978
          telegram-token: ${{ secrets.TG_CI_BOT_TOKEN }}

          release-name: 'Awesome release'
          release-tag: 'v1.0.0'
          release-version: '1.0.0'
