name: "[W] docker-github"

on:
  workflow_dispatch:
    inputs:
      push-dev-versions:
        type: boolean
        description: "Push 'dev' versions"
        required: false
        default: true

      push-branch-latest:
        type: boolean
        description: "Push :<branch>-latest tag"
        required: false
        default: true

      push-release-latest:
        type: boolean
        description: "Push :latest for releases"
        required: false
        default: true

      push-release-latest-major:
        type: boolean
        description: "Push :v<major> for releases"
        required: false
        default: true

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v2

  run:
    needs:
      - init

    uses: milaboratory/github-ci/.github/workflows/docker-github.yaml@v2-beta
    with:
      product-name: 'Docker'
      dockerfile: 'docker/Dockerfile'
      push-dev-targets: ${{ github.repository }}/hello-world
      push-dev-versions: ${{ fromJSON(github.event.inputs.push-dev-versions) }}
      push-branch-latest: ${{ fromJSON(github.event.inputs.push-branch-latest) }}
      push-release-latest: ${{ fromJSON(github.event.inputs.push-release-latest) }}
      push-release-latest-major: ${{ fromJSON(github.event.inputs.push-release-latest-major) }}
      notify-telegram: true

    secrets:
      DOCKER_REGISTRY_USER: ${{ github.actor }}
      DOCKER_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      TELEGRAM_NOTIFICATION_TARGET: "95899978"
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
