name: "[W] java-gradle-lib"

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v2
      - id: context
        uses: milaboratory/github-ci/actions/context@v2

    outputs:
      is-release: ${{ steps.context.outputs.is-release }}

  run:
    needs:
      - init

    uses: milaboratory/github-ci/.github/workflows/java-gradle-lib.yaml@v2-beta
    with:
      java-version: '11'
      lib-name: JAVA Gradle Lib
      lib-name-slug: 'gradle-stub-lib'

      git-crypt-unlock: true
      checkout-submodules: 'recursive'

      build-project: 'stub-lib'
      build-project-dir: './gradle'
      notify-telegram: true
      publish-dev-tasks: publishAllPublicationsToGitHubRepository
      publish-release-tasks: ''
      artifact-paths: |
        libs/*.jar
      release-files: |
        libs/*.jar

    secrets:
      GRADLE_PROPERTIES: |
        miGitHubMavenUser=${{ github.actor }}
        miGitHubMavenToken=${{ secrets.GITHUB_TOKEN }}

      TELEGRAM_NOTIFICATION_TARGET: "95899978"
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}

      GIT_CRYPT_GPG_KEY: ${{ secrets.GIT_CRYPT_GPG_KEY }}
      GIT_CRYPT_KEY_PASSWORD: ${{ secrets.GIT_CRYPT_GPG_KEY_PASSWORD }}
