name: "[W] java-gradle-lib"

on:
  push:
    tags: [ '*' ]
    paths:
      - .github/workflows/wf-java-gradle-lib.yaml

  workflow_dispatch:

jobs:
  run:
    uses: milaboratory/github-ci/.github/workflows/java-gradle-lib.yaml@v1-beta
    with:
      java-version: '11'
      lib-name: JAVA Gradle Lib
      lib-name-slug: 'gradle-stub-lib'
      checkout-submodules: 'recursive'
      build-project: 'stub-lib'
      build-project-dir: './gradle'
      notify-telegram: true
      publish-dev-tasks: publishAllPublicationsToGitHubRepository
      publish-release-tasks: publishMavenPublicationToGitHubRepository
      artifacts-paths: |
        libs/*.jar
      release-files: |
        ./libs/*.jar

    secrets:
      GRADLE_PROPERTIES: |
        miGitHubMavenUser=${{ github.actor }}
        miGitHubMavenToken=${{ secrets.GITHUB_TOKEN }}

      TELEGRAM_NOTIFICATION_TARGET: "95899978"
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
