name: "[W] java-build-gradle-app"

on:
  push:
    tags: [ '*' ]
    paths:
      - .github/workflows/wf-java-gradle-build-app.yaml
      - gradle/stub-app/

  workflow_dispatch:

jobs:
  run:
    uses: milaboratory/github-ci/.github/workflows/java-build-gradle-app.yaml@v1-beta
    with:
      java-version: '11'
      app-name: JAVA Gradle App
      app-name-slug: 'gradle-stub-app'
      build-project: 'stub-app'
      build-project-dir: './gradle'

      release-to-s3: true
      notify-telegram: true

    secrets:
      GRADLE_PROPERTIES: |
        miGitHubMavenUser=${{ github.actor }}
        miGitHubMavenToken=${{ secrets.GITHUB_TOKEN }}

      AWS_KEY_ID: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
      AWS_KEY_SECRET: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

      TELEGRAM_NOTIFICATION_TARGET: "95899978"
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
