name: "[W] node-build-electron-app"

on:
  push:
    tags: [ '*' ]
    paths:
      - .github/workflows/wf-node-electron-build-app.yaml

  workflow_dispatch:

jobs:
  run:
    uses: milaboratory/github-ci/.github/workflows/node-build-electron-app.yaml@v1-beta
    with:
      node-version: '14.x'
      os: |
        ['ubuntu-latest']
      app-name: Node Electron
      app-name-slug: 'some-test-app'
      build-script-name: 'electron:build'
      notify-telegram: true
    secrets:
      TELEGRAM_NOTIFICATION_TARGET: "95899978"
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
