name: "_ [Experiments]"

on:
  push:
    paths:
      - .github/workflows/workflow-experiments.yaml

  workflow_dispatch:

jobs:
  experiment:
    runs-on: ubuntu-latest

    steps:
      - uses: milaboratory/github-ci/actions/context/init@v1
        env:
          MISH_DEBUG: 'true'
          GHWA_ECHO_COMMANDS: 'on'

      - id: get
        uses: milaboratory/github-ci/actions/context/get@v1
        env:
          MISH_DEBUG: 'true'
          GHWA_ECHO_COMMANDS: 'on'
        with:
          key: "versions.json"

      - shell: bash
        run: |
          echo "${{ steps.get.outputs.value }}"
