name: "_ [Experiments]"

on:
  push:
    paths:
      - .github/workflows/workflow-experiments.yaml

  workflow_dispatch:

jobs:
  not-started:
    runs-on: ubuntu-latest
    if: "'true' == 'false'"

    steps:
      - shell: bash
        run: 'true'

    outputs:
      started: 'true'

  check:
    runs-on: ubuntu-latest

    if: always()
    needs:
      - not-started

    steps:
      - shell: bash
        run: |
          echo "Started: '${{ needs.not-started.outputs.started }}'"


#  git-version:
#    strategy:
#      matrix:
#        os:
#          - ubuntu-latest
#          - macos-latest
#          - windows-latest
#
#    runs-on: ${{ matrix.os }}
#
#    steps:
#      - shell: bash
#        run: git --version

#  fail:
#    runs-on: ubuntu-latest
#    steps:
#      - shell: bash
#        run: 'false'
#
#    outputs:
#      status: ${{ job.status }}
#
#  depend:
#    runs-on: ubuntu-latest
#
#    needs:
#      - fail
#
#    steps:
#      - shell: bash
#        run: "true"
#
#    outputs:
#      status: ${{ job.status }}
#
#  check:
#    runs-on: ubuntu-latest
#    if: always()
#    needs:
#      - depend
#
#    steps:
#      - shell: bash
#        env:
#          DEPEND_STATUS: ${{ needs.depend.outputs.status }}
#        run: |
#          echo "Depend status is: '${JOIN_STATUS}'"
