name: "_ [Experiments]"

on:
  push:
    paths:
      - .github/workflows/workflow-experiments.yaml

  workflow_dispatch:

jobs:
  join:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: "true"
      - id: step2
        if: "'a' == 'b'"
        shell: bash
        run: 'true'

    outputs:
      status: ${{ job.status }}
      step2: ${{ toJSON(steps.step2) }}

  check:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - join

    steps:
      - shell: bash
        env:
          JOIN_STATUS: ${{ needs.join.outputs.status }}
          STEP2_INFO: ${{ needs.join.outputs.step2 }}
        run: |
          echo "Join status is: '${JOIN_STATUS}'"
          echo "Step2 info: '${STEP2_INFO}'"
