name: "_ [Experiments]"

on:
  push:
    paths:
      - .github/workflows/workflow-experiments.yaml

  workflow_dispatch:

jobs:
  experiment:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - shell: bash
        run: |
          echo "Time is: ${EPOCHREALTIME}"
