name: "_ [Experiments]"

on:
  push:
    paths:
      - .github/workflows/workflow-experiments.yaml

  workflow_dispatch:

jobs:
  experiment:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: |
          # This step always fails
          exit 1

    outputs:
      status: ${{ job.status }}

  check:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - experiment

    steps:
      - shell: bash
        env:
          DEP_STATUS: ${{ needs.experiment.outputs.status }}
        run: |
          echo "Experiment status is: '${DEP_STATUS}'"
