name: "_ [Experiments]"

on:
  push:
    paths:
      - .github/workflows/workflow-experiments.yaml

  workflow_dispatch:

jobs:
  experiment:
    strategy:
      matrix:
        i:
          - os: ubuntu-latest
            code: 1
          - os: macos-latest
            code: 0
          - os: windows-latest
            code: 0

    runs-on: ${{ matrix.i.os }}

    steps:
      - shell: bash
        run: |
          exit ${{ matrix.i.code }}

    outputs:
      status: ${{ job.status }}

  join:
    runs-on: ubuntu-latest

    needs:
      - experiment

    steps:
      - shell: bash
        run: "true"

    outputs:
      status: ${{ job.status }}

  check:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - experiment
      - join

    steps:
      - shell: bash
        env:
          EXP_STATUS: ${{ needs.experiment.outputs.status }}
          JOIN_STATUS: ${{ needs.join.outputs.status }}
        run: |
          echo "Experiment status is: '${EXP_STATUS}'"
          echo "Join status is: '${JOIN_STATUS}'"
