name: "_ [Experiments]"

on:
  push:
    paths:
      - .github/workflows/workflow-experiments.yaml

  workflow_dispatch:

jobs:
  experiment:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: |
          # This step always fails
          exit 1

      - uses: milaboratory/github-ci/actions/shell@v1
        id: status
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
        with:
          run: |
            echo "${JOB_STATUS}"

    outputs:
      status: ${{ steps.status.outputs.stdout }}

  check:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - experiment

    steps:
      - shell: bash
        env:
          DEP_STATUS: ${{ needs.experiment.outputs.status }}
        run: |
          echo "Experiment status is: '${DEP_STATUS}'"
